# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: blank # the website title (if blank, full name will be used instead)

first_name: Zhongxuan

middle_name: 

last_name: Wu

language_names:
  en: "Zhongxuan Wu"
  zh: "吴中璇"

language_profile:
  en:
    position: Ph.D. Student
    affiliation: UT Austin
    affiliation_short: UT Austin
    location: Austin
    email_label: Email
    scholar_label: Google Scholar
  zh:
    position: Ph.D. 学生
    affiliation: UT Austin
    affiliation_short: UT Austin
    location: Austin
    email_label: 邮箱
    scholar_label: 谷歌学术

keywords: jekyll, jekyll-theme, academic-website, portfolio-website, computational neuroscience, psychology, cognitive sciences, machine learning # add your own keywords or leave empty

icon: campfire.png # the emoji used as the favicon (alternatively, provide image name in /assets/img/)

url: https://zhongxuanwu.github.io # the base hostname & protocol for your site

baseurl:  # the subpath of your site, e.g. /blog/. Leave blank for root

last_updated: false # set to true if you want to display last updated in the footer

impressum_path: # set to path to include impressum link in the footer, use the same path as permalink in a page, helps to conform with EU GDPR

back_to_top: true # set to false to disable the back to top button

position: Ph.D. Student

affiliation:

affiliation_short: UT Austin

location: Austin

email: zhongxuanwu [at] utexas [dot] edu

scholar_userid: mm1AGEkAAAAJ

orcid_id: # 0009-0006-3507-0983

github_username: ZhongxuanWu

researchgate_username:

cv_url:

sidebar_img: profile.png

# -----------------------------------------------------------------------------
# Permalinks
# -----------------------------------------------------------------------------

permalink: /blog/:year/:title/

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  books:
    output: true
  news:
    defaults:
      layout: post
    output: true
  projects:
    output: true

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

markdown: kramdown

highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

include: ["_pages", "_scripts"]

exclude:
  - bin/
  - CONTRIBUTING.md
  - CONTRIBUTING.pt-br.md
  - CUSTOMIZE.md
  - CUSTOMIZE.pt-br.md
  - FAQ.md
  - FAQ.pt-br.md
  - Gemfile
  - Gemfile.lock
  - gs/
  - INSTALL.md
  - INSTALL.pt-br.md
  - LICENSE
  - package.json
  - package-lock.json
  - playwright.config.js
  - playwright-report/
  - purgecss.config.js
  - README.md
  - README.pt-br.md
  - readme_preview/
  - requirements.txt
  - scripts/
  - test/
  - test-results/
  - tests/
  - UPGRADING.md
  - vendor

keep_files:
  - CNAME
  - .nojekyll

plugins:
  - jekyll-archives-v2
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-jupyter-notebook
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-polyglot
  - jekyll-regex-replace
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-tabs
  - jekyll-terser
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji

defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

sass:
  sourcemap: never
  style: compressed

# -----------------------------------------------------------------------------
# Jekyll Polyglot
# -----------------------------------------------------------------------------

languages: ["en", "zh"]

default_lang: "en"

language_labels:
  en: "EN"
  zh: "中"

exclude_from_localization: ["assets"]

lang_from_path: true

country_flag: false # set true for allowing flag symbol in language toggle

parallel_localization: false
